### ISSUE TITLE
zeta(z) is not consistent

### ISSUE THREAD

**Issue by Haks1** [wgxli/complex-function-plotter#12]
Hi,

I like this tool, but it seems getting some wrong values on `zeta(z)`, I tried a slice on Mathematica 13.0 (using `ComplexPlot3D[Zeta[z], ..]`) and the results are not the same.

That's sad because I lost 2 days thinking I've solved a mystery...

Thanks,

**Comment by Haks1** [comment]
I just realized that you've coded the complex zeta logic by yourself in Javascript.

I'm not doubting your expertise, but I'm more doubting about Javascript Math logic, a language well known for not being accurate.

I don't know if they behave well, but I found some other JS zeta functions:

https://github.com/math-io/riemann-zeta
https://github.com/stdlib-js/math-base-special-riemann-zeta

I don't have time this days to investigate, but I really wish to understand what was the mistake in your zeta version, because the bug is interesting.

**Comment by wgxli** [comment]
Hi,

Could you comment on exactly which slice you tried plotting?

The plotter is not accurate for very high imaginary values along the critical strip. This is a design choice - the best known algorithms are very computationally demanding for high imaginary components, and I needed to make a compromise between responsiveness (real-time) and accuracy. My focus was to make a fun tool to "play around with" and get a feel for the functions; I leave the computationally demanding/exact computations to other tools (Mathematica).

If the slice you're talking about is close to the origin, though, I will take a look and fix the problem.

**Comment by Haks1** [comment]
Hello,

Thank you for your answer.
I don't remember exactly, but I was less than 5000i.

Can you detail me a bit the exact trade-off you took here in terms of the original function equation ?
Can you express the equation of your zeta ?

**Comment by wgxli** [comment]
The Riemann zeta function in the critical strip is computed via the Riemann-Siegel formula. (Code [here](https://github.com/wgxli/complex-function-plotter/blob/6c929eac58482eaa24abc3626bf1afaebcb7e3ac/src/gl-code/complex-functions.js#L250).)

I use 32 terms on mobile and 64 on desktop. This gives good accuracy up to ~150i on desktop. The convergence goes roughly as 1/sqrt(n), where n is the number of terms. So to get up to 5000i, I'd need ~70000 terms, which is not possible in real-time.

I use a slight hack to improve the accuracy by averaging estimates of zeta(z) and zeta(1-z) in a non-holomorphic way. I don't think there's any existing theoretical work on the efficacy of this hack. This gives qualitatively OK results up to ~400i on desktop. Even with this improvement, though, I'd still need ~500 terms to get up to 5000i.

**Comment by farteryhr** [comment]
![image](https://user-images.githubusercontent.com/1175749/170522087-05a9c9a4-cd8a-488c-88dd-c315bd31b6a8.png)
*kaboom*
and yeah i find this plotter nice and fun to play with.
i'm also interested in how numerical computation of special functions work, and the visualization of how the floating point numbers fail.
better to have a notice in the help panel (or when specific functions are used)?

**Comment by Haks1** [comment]
Hi,

Thank you so much Samuel for this great tool.

In fact, I love it, I love the custom functions.

You can forget about my issue and close it when you want, I kinda understand how it's not that interesting.

I mean, it's kinda interesting, but I found some way better stuff than that to dig in.

I learned and discovered a lot about Math with this tool and with custom functions, I just wish to see more in that space, like the contour integrals (on the current feature on normal functions, I'm not sure to understand it well for the moment, I lack some knowledge here, but I see we can locate peaks, but not really zeros).

I found some interesting fractals (I rediscovered a lot of stuff, but I think I'm getting close to some new content) but I struggle to pinpoint the exact zeros' values for exemple (6 to 8 digits is great, but sometimes not enough) .
I did some little features, you might want to implement them as classic feature.

Also, do you have some C language version using GLSL ?
If we can get rid of the limitation of the browser, I'm in.
I don't do that much open source projects with GitHub and it's not like I got a lot of free time to dev, but I would be happy to help improve it, so I'm open if you wanna discuss with me.

On a different topic, I wish to understand the black points (on mandelbrot for exemple, what is the `vec2` value of outer black points ? `undefined` ?).

Thanks,

**Comment by wgxli** [comment]
Forgot to update this issue - on desktop, zeros are now reasonably accurate (within ~0.02) up to at least 5000i.
