### ISSUE TITLE
graphical discontinuity

### ISSUE THREAD

**Issue by farteryhr** [wgxli/complex-function-plotter#16]
`abs(sin(sqrt(z))/sqrt(z))-1`, near 33.23+33.23i
![image](https://user-images.githubusercontent.com/1175749/184541414-7a26fe8f-3407-4e99-94fe-7ba716f6fb9e.png)

btw i thought it was parabola (turns out no), and i wanted to get its parameter by finding where x+xi is a root. and i found something more there!

last time i could find such big glitch (by precision loss that i could imagine) is on (1-cos(z))/z^2 near the origin with checkerborard turned on.

but yes also `abs((1-cos(sqrt(z)))/z)-1/2` near 132.92+132.92i.

is this unavoidable with GPU precision?

**Comment by wgxli** [comment]
Unfortunately, this is unavoidable with GPU precision (at least if I want to have widespread support on all devices). I am already using the highest precision available with WebGL 1.

More precision would, of course, just push the issue down the road. There will always be sufficiently pathological functions that will require more than the available number of bits. (Unless I can implement arbitrary-precision arithmetic on the GPU - which would not be easy.)

**Comment by wgxli** [comment]
Mostly fixed in latest update - range has been expanded by a massive amount, by some quasi-arbitrary precision trickery.

**Comment by farteryhr** [comment]
![image](https://github.com/user-attachments/assets/5d0a4a3d-4410-47e1-bb54-e7fff18f851e)
![image](https://github.com/user-attachments/assets/a9060c08-51ea-4949-b767-a45330c89533)
just found another unexpected spot... is it reflection formula, how does it fail so much?

**Comment by wgxli** [comment]
Will investigate - of note is that gamma(z/pi) shows this issue, but not gamma(z/t) with t set to pi.

**Comment by wgxli** [comment]
Fixed in latest update.
